apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" $ }}-nginx
  labels:
  {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value }}
  {{- end }}
data:
  nginx.conf: {{ .Values.nginx.config | quote }}