apiVersion: v1
kind: Service
metadata:
  labels:
  {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value }}
  {{- end }}
  name: {{ template "fullname" $ }}
spec:
  ports:
  - name: http
    protocol: TCP
    targetPort: http
    port: 80
  selector:
  {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value }}
  {{- end }}