apiVersion: v1
appVersion: 0.0.1
home: https://github.com/express42/helm-charts/
maintainers:
- email: nvelgin@express42.com
  name: Nikita Velgin
name: prometheus-telegram-bot
sources:
- https://github.com/inCaller/prometheus_bot
version: 0.1.3
