apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" $ }}-template
  labels:
  {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value }}
  {{- end }}
data:
  template.tmpl: |-
{{ .Files.Get "alert-templates/default.tmpl" | indent 4 }}



