apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" $ }}-config
  labels:
  {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value }}
  {{- end }}
data:
  config.yaml: |
    telegram_token: {{ .Values.telegram_token }}
    template_path: {{ .Values.template_path }}
    time_zone: {{ .Values.time_zone }}
    split_token: {{ .Values.split_token }}
    time_outdata: {{ .Values.time_outdata }}
    split_msg_byte: {{ .Values.split_msg_byte }}

