apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" $ }}
  labels:
  {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value }}
  {{- end }}
spec:
  selector:
  {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value }}
  {{- end }}
  ports:
    - protocol: TCP
      port: 9087
      targetPort: 9087